CREATE DATABASE ONTAPB2

USE ONTAPB2

/*
Tạo bảng kho sách : mã kho, mã sách, số lượng
Tạo bảng sách : mã sách, tên sách, tác giả
Tạo bảng phiếu mượn: mã phiếu, mã sách, tên sinh viên, trạng thái, ngày mượn, số lượng mượn
Viết proc insert bảng sách nếu mã sách đã tồn tại -> hiển thị sách đã tồn tại
Viết proc insert bảng kho sách
Viết proc insert bảng phiếu mượn, nếu mã sách không tồn tại -> thông báo sách không tồn tại, nếu số lượng mượn > số lượng sách trong kho
-> thông báo không đủ sách cho mượn, trường hợp insert thành công -> update lại số lượng sách trong kho = số lượng - số lượng mượn
Viết proc trả sách : update lại trạng thái của phiếu mượn, đồng thời update lại số lượng sách trong kho
Viết view hiển thị top 2 sách có lượt mượn nhiều nhất
Viết view hiển thị tên sinh viên và sách mượn
Viết hàm nhận vào mã sách -> hiển thị số lượt mượn của sách
Viết hàm nhận vào mã sách -> hiển thị sinh viên chưa trả sách
*/

CREATE TABLE LOAISACH(
MALOAI CHAR(10) NOT NULL,
MASACH CHAR(10) NOT NULL,
SOLUONG INT,
)
ALTER TABLE LOAISACH ADD CONSTRAINT PK_MALOAI PRIMARY KEY(MALOAI)
ALTER TABLE LOAISACH ADD CONSTRAINT FK_MASACH FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)

CREATE TABLE SACH(
MASACH CHAR(10) NOT NULL,
TENSACH VARCHAR(30),
TACGIA VARCHAR(30),
)
ALTER TABLE SACH ADD CONSTRAINT PK_MASACH PRIMARY KEY(MASACH)

CREATE TABLE PHIEUMUON(
MAPHIEU CHAR(10) NOT NULL,
MASACH CHAR(10) NOT NULL,
TENSINHVIEN VARCHAR(30),
TRANGTHAI VARCHAR(20),
NGAYMUON DATE,
SLMUON INT
)
ALTER TABLE PHIEUMUON ADD CONSTRAINT PK_MAPHIEU PRIMARY KEY (MAPHIEU)
ALTER TABLE PHIEUMUON ADD CONSTRAINT FK_MASACHPM FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)

CREATE PROCEDURE INSERT_SACH @MASACH CHAR(10),@TENSACH VARCHAR(30),@TACGIA VARCHAR(30)
AS
BEGIN
	IF EXISTS (SELECT MASACH FROM SACH WHERE @MASACH = MASACH)
		BEGIN
			PRINT 'MA SACH DA TON TAI'
		END
	ELSE
		BEGIN
			INSERT INTO SACH VALUES (@MASACH,@TENSACH,@TACGIA)
		END
END

EXEC INSERT_SACH 'MS1','DOREMON','KIM DONG'
EXEC INSERT_SACH 'MS2','CONAN','KIM LAN'
EXEC INSERT_SACH 'MS3','POKEMON','VAN DONG'
EXEC INSERT_SACH 'MS4','DRAGON BALL','XUAN DUONG'
EXEC INSERT_SACH 'MS5','TAM LY HOC','VAN THIEN'

CREATE PROCEDURE INSERT_LOAISACH @MALOAI CHAR(10),@MASACH CHAR(10),@SOLUONG INT
AS
BEGIN
	IF EXISTS (SELECT MALOAI FROM LOAISACH WHERE @MALOAI = MALOAI)
		BEGIN
			PRINT 'MA KHO DA TON TAI'
		END
	ELSE
		BEGIN
			INSERT INTO LOAISACH VALUES (@MALOAI,@MASACH,@SOLUONG)
		END
END

SELECT * FROM LOAISACH
SELECT * FROM SACH
EXEC INSERT_LOAISACH 'MK1','MS1',100
EXEC INSERT_LOAISACH 'MK2','MS2',100
EXEC INSERT_LOAISACH 'MK3','MS5',100
DELETE FROM LOAISACH
DELETE FROM SACH
DELETE FROM PHIEUMUON
/*
Viết proc insert bảng phiếu mượn, nếu mã sách không tồn tại -> thông báo sách không tồn tại, nếu số lượng mượn > số lượng sách trong kho
-> thông báo không đủ sách cho mượn, trường hợp insert thành công -> update lại số lượng sách trong kho = số lượng - số lượng mượn
*/
CREATE PROCEDURE INSERT_PHIEUMUON @MAPHIEU CHAR(10),@MASACH CHAR(10),@TENSINHVIEN VARCHAR(30),@TRANGTHAI VARCHAR(20),@NGAYMUON DATE,@SLMUON INT
AS
BEGIN
	IF NOT EXISTS (SELECT MASACH FROM SACH WHERE @MASACH = MASACH)
		BEGIN
			PRINT 'SACH KHONG TON TAI' 
		END
	ELSE
		BEGIN
			IF(@SLMUON > (SELECT SOLUONG FROM LOAISACH WHERE MASACH = @MASACH))
				BEGIN
					PRINT 'KHONG DU SACH CHO MUON'
				END
			ELSE
				BEGIN
					INSERT INTO PHIEUMUON VALUES (@MAPHIEU,@MASACH,@TENSINHVIEN,@TRANGTHAI,@NGAYMUON,@SLMUON)
					UPDATE LOAISACH
					SET SOLUONG = SOLUONG - @SLMUON
					WHERE MASACH = @MASACH
				END
		END
END
DROP PROCEDURE INSERT_PHIEUMUON
EXEC INSERT_PHIEUMUON '1','MS1','NGUYEN CONG THANG','CHUA TRA','2022-5-20',50
EXEC INSERT_PHIEUMUON '2','MS1','NGUYEN CONG A','CHUA TRA','2022-5-20',20
EXEC INSERT_PHIEUMUON '3','MS2','NGUYEN CONG B','CHUA TRA','2022-5-20',20
EXEC INSERT_PHIEUMUON '4','MS5','NGUYEN CONG C','CHUA TRA','2022-5-21',10
EXEC INSERT_PHIEUMUON '5','MS5','NGUYEN VAN B','CHUA TRA','2022-5-21',5

SELECT * FROM LOAISACH
SELECT * FROM PHIEUMUON
--Viết proc trả sách : update lại trạng thái của phiếu mượn, đồng thời update lại số lượng sách trong kho
CREATE PROCEDURE TRA_SACH @MAPHIEU CHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT MAPHIEU FROM PHIEUMUON WHERE MAPHIEU  = @MAPHIEU)
		BEGIN 
			PRINT 'KHONG CO MA PHIEU NAY'
		END
	ELSE
		BEGIN
			UPDATE PHIEUMUON SET TRANGTHAI = 'DA TRA' WHERE MAPHIEU = @MAPHIEU
			DECLARE @SLMUON INT = (SELECT SLMUON FROM PHIEUMUON WHERE MAPHIEU = @MAPHIEU)
			DECLARE @MASACH CHAR(10) = (SELECT MASACH FROM PHIEUMUON WHERE MAPHIEU = @MAPHIEU)
			UPDATE LOAISACH SET SOLUONG = SOLUONG + @SLMUON WHERE MASACH = @MASACH
		END
END
EXEC TRA_SACH '2'
SELECT * FROM LOAISACH
--Viết view hiển thị top 2 sách có lượt mượn nhiều nhất
--Viết view hiển thị tên sinh viên và sách mượn
CREATE VIEW VIEWLUOTMUON
AS
SELECT TOP 2 B.MASACH,B.TENSACH FROM PHIEUMUON A INNER JOIN SACH B ON A.MASACH = B.MASACH
GROUP BY B.MASACH,B.TENSACH 
ORDER BY SUM(A.SLMUON) DESC

SELECT * FROM VIEWLUOTMUON

CREATE VIEW HIENTHI_TENSV
AS
SELECT A.TENSINHVIEN,B.MASACH,B.TENSACH FROM PHIEUMUON A INNER JOIN SACH B ON A.MASACH = B.MASACH

SELECT * FROM HIENTHI_TENSV

--Viết hàm nhận vào mã sách -> hiển thị số lượt mượn của sách
--Viết hàm nhận vào mã sách -> hiển thị sinh viên chưa trả sách

CREATE FUNCTION SLMUONCUASACH (@MASACH CHAR(10))
RETURNS INT
AS
BEGIN
	RETURN (SELECT COUNT(MASACH) FROM PHIEUMUON WHERE MASACH = @MASACH)
END

PRINT 'SO LUOT MUON CUA SACH LA: ' + CAST(DBO.SLMUONCUASACH('MS1') AS VARCHAR)

CREATE FUNCTION HIENTHI_SINHVIEN (@MASACH CHAR(10))
RETURNS TABLE
AS
	RETURN (SELECT TENSINHVIEN FROM PHIEUMUON WHERE MASACH = @MASACH AND TRANGTHAI = 'CHUA TRA')
GO

SELECT * FROM DBO.HIENTHI_SINHVIEN('MS5')
























